spring:
    application:
        name: enterprise-business-management-system
    datasource:
            url: jdbc:mysql://localhost:3306/ebms
            username: root
            password: root

    jpa:
        hibernate:
            ddl-auto: update

        show-sql: true

        properties:
            hibernate:
                format_sql: true

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    '[org.springframework.web]': DEBUG